apiVersion: v1
kind: Service
metadata:
  name: pixelated-service
  namespace: pixelated-staging
  labels:
    app: pixelated-app
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4321
      protocol: TCP
      name: http
  selector:
    app: pixelated-app
