apiVersion: v1
kind: ResourceQuota
metadata:
  name: cert-manager-hard-limits
  namespace: cert-manager
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: 1Gi
    limits.cpu: "3"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: metoro-hard-limits
  namespace: metoro
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

