apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-ingress
  namespace: pixelated-staging
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - staging-azure.pixelatedempathy.com
      secretName: pixelated-staging-tls
  rules:
    - host: staging-azure.pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-ingress
  namespace: pixelated-production
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - azure.pixelatedempathy.com
      secretName: pixelated-production-tls
  rules:
    - host: azure.pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
