---
apiVersion: v1
kind: Namespace
metadata:
  name: pixelated-staging
  labels:
    name: pixelated-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: pixelated-production
  labels:
    name: pixelated-production
    environment: production