apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: pixelated
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "" # Will be created via: kubectl create secret docker-registry acr-secret --namespace pixelated --docker-server=pixelatedregistry.azurecr.io --docker-username=<acr-username> --docker-password=<acr-password>
