apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated
  namespace: pixelated
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - pixelatedempathy.com
        - www.pixelatedempathy.com
      secretName: pixelated-tls-cert
  rules:
    - host: pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated
                port:
                  number: 80
    - host: www.pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated
                port:
                  number: 80
