apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- pixelated-kustomization.yaml
- flux-namespace-secret-role.yaml
- image-automation.yaml
patchesStrategicMerge:
- flux-clusterrole-secrets-patch.yaml
