---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pixelated
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/pixelkube/pixelated
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pixelated
  timeout: 5m0s
  retryInterval: 2m0s
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: pixelated
      namespace: pixelated

